stages:
  - tsa_run

tests:
  stage: tsa_run
  image: mcr.microsoft.com/playwright:v1.28.0-focal
  parallel:
    matrix:
      - PROJECT: ['chromium']
        SHARD_INDEX: [1]
        SHARD_TOTAL: 1
  script:
    - npm install ci
    - npm install -D @playwright/test
    - npm ci
    - npx playwright test --project=$PROJECT --shard=$SHARD_INDEX/$SHARD_TOTAL
  timeout: 4 hours 30 minutes
  artifacts:
    paths:
      - ./playwright-report/
      - ./Screenshot/
    when: always
    expire_in: 3 days
