stages:
    - st-checks

fac_smoke_tests:
    stage: st-checks
    image: 
        name: postman/newman_alpine33
        entrypoint: [""]
    script:
        - newman --version
        - npm install -g newman-reporter-html newman-reporter-htmlextra
        - newman run  Final_SmokeTests.postman_collection.json  -e Final_FCURL1.0.postman_environment.json -d Data_driven.json --reporters cli,htmlextra,junit --reporter-htmlextra-export report.html --reporter-junit-export report.xml
    artifacts:
        when: always
        paths:
            - report.html
        reports:
            junit: report.xml
            
